### PR TITLE
Changed plugin until to latest build

### PR DESCRIPTION
**Pull request by bhushan**
I am using latest build (212.*) which is not supported by current build 

I am not sure, Is this really required, So raising PR, So you can decide !!

### CODE REVIEW

**Comment by jiyuan0125** [comment]
These two variables come from intellij-platform-plugin-template, in fact, I did not use these two variables. Because the functions provided in the jetbrains plug-in SDK are not used, I don't think it makes sense to maintain the applicable version number. Then I temporarily comment out these two variables.

**Comment by bhushan** [comment]
> These two variables come from intellij-platform-plugin-template, in fact, I did not use these two variables. Because the functions provided in the jetbrains plug-in SDK are not used, I don't think it makes sense to maintain the applicable version number. Then I temporarily comment out these two variables.

Aha ! so we dont even need those variables as well right ? we could remove it ?

**Comment by jiyuan0125** [comment]
Yes, it can be completely removed

**Comment by bhushan** [comment]
We could remove it.
I am stuck at resolving `verify` workflow. Release Draft and other worflow are working like a charm also `test` workflow is not helpful for us as we dont use TDD or write tests

**Comment by jiyuan0125** [comment]
The purpose of verification should be to check whether the APIs used are compatible. We are not using APIs. I want to delete this verification step. What do you think?

**Comment by jiyuan0125** [comment]
Otherwise, I need to update the jdk used to 11 version, in order to pass the verification.

**Comment by bhushan** [comment]
I actually spent lot of time in debugging, also i tried without verification step, it works as expected and also you are right we are not going to use ani api so its should be removed as of now at-least, your take is right 👍🏻

**Comment by bhushan** [comment]
I tried with zule jdk 16 had same issue with verify workflow

**Pull request closed without merging**
